export type IconName =
  | 'home'
  | 'explore'
  | 'messages'
  | 'notifications'
  | 'profile'
  | 'arrow-left'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-down'
  | 'close'
  | 'check'
  | 'add'
  | 'image'
  | 'copy'
  | 'trash'
  | 'user-circle'
  | 'loader'
