# Configuration file for Redpanda Connect
# Intended to handle post creation, updating, and deletion in conjunction with OpenSearch

input:
  http_server:
    #address: ""
    timeout: 10s
    rate_limit: ""
    path: /upstream # "${REDPANDA_NEW_POST_API_PATH:/upstream}"
    allowed_verbs: [ POST ]
      #path: "${REDPANDA_REQUEST_HASHTAG_HTTP_API_BASE_URL:/tags}/{hashtag}",
      #prefix: ${REDPANDA_DYNAMIC_HTTP_API_PREFIX:/api}

#buffer:
#  sqlite:
#    path: ./buffer.db

pipeline:
  threads: 4
  processors:
    - mapping: |
        root = this

        meta id = this.data.updateTime${!counter()}
        meta action = this.action

        root.id = this.id
        root.doc = this.body

output:
  #handle_post_cud:
  #  kafka_franz:
  #    topic: "public-topic"
  #    metadata:
  #      exclude_prefixes:
  #        - topic
  opensearch:
    urls: [ http://localhost:9200 ] #"${OPENSEARCH_HTTP_API_BASE_URL:localhost:9200}" ]
    index: "public-posts" # "${OPENSEARCH_PUBLIC_INDEX_NAME:activities}"
    action: ${! @action }
    id: ${! @id }
    type: ""
    max_in_flight: 64
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
    basic_auth:
      enabled: false
      username: ""
      password: ""
    #tls:

#redpanda:
#  seed_brokers: [ "redpanda-0:9092" ]
  #tls:
  #  enabled: true
#  sasl:
#    - mechanism: SCRAM-SHA-256
#      password: "secretpassword" #"${REDPANDA_ADMIN_PASS:secretpassword}"
#      username: "superuser" #"${REDPANDA_ADMIN_USER:superuser}"

